/**
 * Ghost.build REST client (server-side only).
 *
 * GHOST_API_KEY is read from the environment server-side and is never
 * exposed to the client. The key is created with `ghost api-key create`
 * and configured in the Vercel project env.
 *
 * Contract verified against the ghost CLI MCP tool schemas
 * (`ghost mcp get ghost_create|ghost_create_dedicated|ghost_pricing`) and
 * endpoint probing (unauthenticated probes: `/v0/databases/spaces/{space}`
 * is NOT a route; `POST /v0/spaces/{space}/databases` exists — 401
 * `{"message":"unauthorized"}` without a Bearer key):
 * - shared-space databases: POST /spaces/{space}/databases
 *   {name, wait} -> {connection_string, id, name, warnings}
 * - dedicated databases:   POST /spaces/{space}/databases
 *   {name, size, wait, dedicated: true} -> {..., size}
 * Billing is usage-based (per-size compute + per-GiB storage above the
 * included amount); invoices are generated by Ghost per cycle — there is
 * no custom-charge API, so plan pricing stays on the founder's side.
 */

const GHOST_BASE = process.env.GHOST_URL ?? "https://api.ghost.build/v0";

export type GhostPlan = "creator" | "power";

export const GHOST_PLANS: Record<GhostPlan, { kind: "shared" | "dedicated"; size?: string }> = {
  creator: { kind: "shared" },
  power: { kind: "dedicated", size: "1x" },
};

export function ghostApiKeyConfigured(): boolean {
  return Boolean(process.env.GHOST_API_KEY);
}

async function ghostRequest(path: string, body: Record<string, unknown>): Promise<Record<string, unknown>> {
  const key = process.env.GHOST_API_KEY;
  if (!key) {
    throw new Error("GHOST_API_KEY is not configured");
  }
  const res = await fetch(`${GHOST_BASE}${path}`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${key}`,
    },
    body: JSON.stringify(body),
  });
  if (!res.ok) {
    const detail = await res.text().catch(() => "");
    throw new Error(`Ghost API ${res.status}: ${detail.slice(0, 200)}`);
  }
  return (await res.json()) as Record<string, unknown>;
}

export interface GhostProvision {
  id: string;
  name: string;
  size?: string;
  status: "provisioning";
}

/**
 * Provisions the plan's database asynchronously (wait: false — shared
 * databases can take minutes to start; the route must not block).
 * The connection string stays server-side — never returned to the client.
 */
export async function provisionGhostDatabase(plan: GhostPlan): Promise<GhostProvision> {
  const spec = GHOST_PLANS[plan];
  const space = process.env.GHOST_SPACE_ID ?? "personal";
  const name = `aura-${plan}-${Date.now()}`;

  const data =
    spec.kind === "dedicated"
      ? await ghostRequest(`/spaces/${space}/databases`, {
          name,
          size: spec.size,
          wait: false,
          dedicated: true,
        })
      : await ghostRequest(`/spaces/${space}/databases`, { name, wait: false });

  return {
    id: String(data.id ?? ""),
    name: String(data.name ?? name),
    size: data.size ? String(data.size) : undefined,
    status: "provisioning",
  };
}